name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Inject TMDB API Key with Obfuscation
        run: |
          # Create src directory if it doesn't exist (optional, remove if not needed)
          mkdir -p src
          echo "Injecting API Key..."
          echo "const apiKey = '${{ secrets.TMDB_API_KEY }}'.split('').reverse().join('');" > src/apiKey.js
          if [ -f front.js ]; then
            cat src/apiKey.js >> front.js
            echo "/* API Key obfuscated and injected */" >> front.js
            echo "Injection successful, front.js updated."
          else
            echo "Error: front.js not found in root directory."
            exit 1
          fi
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      - name: Build
        run: |
          mkdir -p dist
          cp index.html front.js front.css dist/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Ensure deployment uses the main branch source
          publish_branch: main
