name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Inject TMDB API Key with Obfuscation
        run: |
          echo "const apiKey = '${{ secrets.TMDB_API_KEY }}'.split('').reverse().join('');" > src/apiKey.js
          cat src/apiKey.js >> front.js
          echo "/* API Key obfuscated and injected */" >> front.js
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      - name: Build
        run: |
          mkdir -p dist
          cp index.html front.js front.css dist/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
